services:
  - type: web
    name: legal-ai-assistant
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn legalAI.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: WEB_CONCURRENCY
        value: 4
